# 장기적으로 필요한 것 
* train file 들을 따로 분류해서 저장하고 가지면서 운영할 필요가 있어보임 공모가 1,3,6 트레이딩 정보포함 3,6
* 현재 빠져 있는 것 종속변수 주가수익률
* traiding 에서 쓰일 per pbr
* 시총규모별로 나누기 함수 만들기

In [1]:
import pandas as pd
import numpy as np

# 분모 분자로 재무지표들 계산하기

In [21]:
F = pd.read_csv('Data/KQ_Finance.csv',thousands=',',encoding = 'cp949')

In [22]:
F['Item'].unique()

array(['유동자산', '재고자산', '매출채권및기타채권', '당좌자산', '부채총계', '유동부채', '순부채', '자본총계',
       '매출액', '매출총이익', '영업이익', '당기순이익', '이자비용', 'EBITDA2'], dtype=object)

In [24]:
IPOcoms = F['Name'].unique()

In [25]:
F.set_index(['Name','Item'],inplace = True)

In [27]:
for i in IPOcoms:
    F.loc[(i,'매출총이익률'),:] = F.loc[(i,'매출총이익'),:] / F.loc[(i,'매출액'),:]
    F.loc[(i,'영업이익률'),:] = F.loc[(i,'영업이익'),:] / F.loc[(i,'매출액'),:]
    F.loc[(i,'ROE'),:] = F.loc[(i,'당기순이익'),:] / F.loc[(i,'자본총계'),:]
    F.loc[(i,'유동비율'),:] = F.loc[(i,'유동자산'),:] / F.loc[(i,'유동부채'),:]
    F.loc[(i,'당좌비율'),:] = F.loc[(i,'당좌자산'),:] / F.loc[(i,'유동부채'),:]
    F.loc[(i,'부채비율'),:] = F.loc[(i,'부채총계'),:] / F.loc[(i,'자본총계'),:]
    F.loc[(i,'이자보상배율'),:] = F.loc[(i,'영업이익'),:] / F.loc[(i,'이자비용'),:]
    F.loc[(i,'매출채권회전율'),:] = F.loc[(i,'매출액'),:] / F.loc[(i,'매출채권및기타채권'),:]
    F.loc[(i,'재고자산회전율'),:] = F.loc[(i,'매출액'),:] / F.loc[(i,'재고자산'),:]

In [29]:
def calUp(Series):
    deltas = [0]
    for i in range(len(Series)-1):
        delta = (Series[i+1] - Series[i]) / Series[i]
        deltas.append(delta)
    return deltas

In [30]:
for i in IPOcoms:
    F.loc[(i,'매출액증가율'),:] = calUp(F.loc[(i,'매출액'),:])
    F.loc[(i,'영업이익증가율'),:] = calUp(F.loc[(i,'영업이익'),:])

<ipython-input-29-c50165044131>:4: RuntimeWarning: invalid value encountered in double_scalars
  delta = (Series[i+1] - Series[i]) / Series[i]

In [32]:
F.to_csv('Data/KQ_CalFin.csv')

In [35]:
X_train.index

Index(['메디톡스', '유비쿼스홀딩스', '대성파인텍', '이수앱지스', '중국식품포장', '엔시트론', '코오롱생명과학', '뷰웍스',
       '에스앤에스텍', '에이테크솔루션',
       ...
       '아모그린텍', 'TS트릴리온', 'SNK', '현대무벡스', '컴퍼니케이', '수젠텍', '마이크로디지탈', '까스텔바작',
       '압타바이오', '엠에프엠코리아'],
      dtype='object', name='종목명', length=600)

# Null 확인

In [2]:
X_train= pd.read_csv('CleanData/X_train_1_3(all).csv', encoding = 'cp949')
X_train.set_index('종목명',inplace = True)

# 확정적으로 drop 시킬 컬럼들

In [10]:
cols = ['IPO_PSR','MMF 증감률 ', '국고1년시장금리%p', '국고5년시장금리%p','상장주식수','매출액증가율(YoY)-before','영업이익증가율(YoY)-before'\
       , '당기순이익(지배)','자본총계(지배)','EBITDA2','순부채','매출액','세전계속사업이익']
X_train.drop(cols ,axis =1 , inplace =True)

In [16]:
cols = ['3개월 평균 기관 매도수량 비중(일간)','3개월 평균 기관 매수수량 비중(일간)','1개월 평균 기관 매수수량 비중(일간)','1개월 평균 기관 매도수량 비중(일간)']
X_train.drop(cols ,axis =1 , inplace =True)

In [50]:
cols = ['상장유형','공모가(원)']
X_train.drop(cols ,axis =1 , inplace =True)

C:\Users\HY\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [31]:
X_train['NullCount']  = X_train.isnull().sum(axis = 1)
nullcounts = X_train['NullCount'].unique()
X_train.columns

## 없는 애들 특징
* 23 finance가 다 없는 것 같음, 21도 마찬가지일 듯 이런애들은 
* 1개 없는 애들은 재고자산회전률 이자보상비율 --> 분자분모 단위에서 재계산필요
* 2개는 1개와 동일 매출채권회전률 추가
* 3개 당좌 매출액증가율
* 
* 
* 
* 
* 
* 14개 없는건 그냥 빠져야함

In [43]:
X_train = X_train[X_train['NullCount']!=14]

In [44]:
X_train.isnull().sum()

상장유형                       0
공모가(원)                     0
상장일                        0
IPO시가총액                    0
매출총이익률                     2
영업이익률                      2
ROE(지배)                   76
매출액증가율(YoY)               81
영업이익증가율(YoY)              76
유동비율                       2
당좌비율                       8
부채비율                       0
이자보상배율                    59
매출채권회전율                   88
재고자산회전율                  147
IPO_PER                    0
IPO_PBR                    1
IPO_EV/EBIDTA              2
1개월 시가총액회전율                0
3개월 시가총액회전율                0
1개월 평균 거래량회전율              0
3개월 평균 거래량회전율              0
1개월 평균 일중변동률               0
3개월 평균 일중변동률               0
1개월 평균 개인 매도수량 비중(일간)      0
3개월 평균 개인 매도수량 비중(일간)      0
1개월 평균 개인 매수수량 비중(일간)      0
3개월 평균 개인 매수수량 비중(일간)      0
시장수익률                      0
1개월 시장 회전율                 0
3개월 시장 회전율                 0
M2 증감률                     0
고객예탁금 증감률                  0
국고3년시장금리%p                 0
NullCount                  0
dtype: int64

In [32]:
X_train['NullCount'].value_counts()

0     398
1      84
5      71
14     15
2      14
4       6
6       5
3       3
7       2
Name: NullCount, dtype: int64

In [33]:
nullcounts

array([ 0,  1,  2,  3,  7,  8, 23,  4,  5,  6, 21,  9, 10], dtype=int64)

In [60]:
X_train[X_train['NullCount'] == 6]

,상장일,IPO시가총액,매출총이익률,영업이익률,ROE(지배),매출액증가율(YoY),영업이익증가율(YoY),유동비율,당좌비율,부채비율,...,3개월 평균 개인 매도수량 비중(일간),1개월 평균 개인 매수수량 비중(일간),3개월 평균 개인 매수수량 비중(일간),시장수익률,1개월 시장 회전율,3개월 시장 회전율,M2 증감률,고객예탁금 증감률,국고3년시장금리%p,NullCount
종목명,,,,,,,,,,,,,,,,,,,,,
선데이토즈,2010-11-10,20928000000,100.00,30.58,NaN,NaN,NaN,25068.21,25068.21,0.33,...,89.517619,93.761739,90.794444,0.029279,40.102631,121.363974,0.069670,0.239225,-1.200,6
큐브엔터,2013-11-21,14000000000,16.45,0.91,NaN,NaN,NaN,127.44,127.44,167.26,...,68.360417,94.150526,89.393333,0.075479,22.473670,73.963342,0.044318,-0.071408,0.040,6
한국정보인증,2014-02-04,48537000000,100.00,14.05,NaN,NaN,NaN,193.55,191.28,50.64,...,97.613810,99.070952,98.960635,-0.003970,27.722998,91.740920,0.049371,-0.135951,0.164,6
셀리드,2019-02-20,311559336000,NaN,NaN,188.66,NaN,-42.84,113.45,113.45,-189.79,...,93.246066,96.716500,96.390000,-0.194433,35.255991,105.215234,0.058281,-0.087165,-0.502,6
까스텔바작,2019-06-10,79160400000,63.15,15.78,NaN,NaN,NaN,441.99,196.22,26.25,...,96.765606,96.855217,96.772273,-0.177420,41.861948,123.272488,0.062603,-0.019534,-0.470,6

In [59]:
X_train[X_train['NullCount'] == 6].isnull().sum()

상장일                      0
IPO시가총액                  0
매출총이익률                   1
영업이익률                    1
ROE(지배)                  4
매출액증가율(YoY)              5
영업이익증가율(YoY)             4
유동비율                     0
당좌비율                     0
부채비율                     0
이자보상배율                   5
매출채권회전율                  5
재고자산회전율                  5
IPO_PER                  0
IPO_PBR                  0
IPO_EV/EBIDTA            0
1개월 시가총액회전율              0
3개월 시가총액회전율              0
1개월 평균 거래량회전율            0
3개월 평균 거래량회전율            0
1개월 평균 일중변동률             0
3개월 평균 일중변동률             0
1개월 평균 개인 매도수량 비중(일간)    0
3개월 평균 개인 매도수량 비중(일간)    0
1개월 평균 개인 매수수량 비중(일간)    0
3개월 평균 개인 매수수량 비중(일간)    0
시장수익률                    0
1개월 시장 회전율               0
3개월 시장 회전율               0
M2 증감률                   0
고객예탁금 증감률                0
국고3년시장금리%p               0
NullCount                0
dtype: int64

In [35]:
X_train = X_train.loc[:,:"재고자산회전율"]

In [36]:
X_train

,상장유형,공모가(원),상장일,상장주식수,IPO시가총액,매출총이익률,영업이익률,ROE(지배),매출액증가율(YoY),영업이익증가율(YoY),매출액증가율(YoY)-before,영업이익증가율(YoY)-before,유동비율,당좌비율,부채비율,이자보상배율,매출채권회전율,재고자산회전율
종목명,,,,,,,,,,,,,,,,,,
메디톡스,신규상장,14000,2009-01-16,5059000,70826000000,65.70,30.26,12.17,44.70,4.72,878.15,235.17,743.39,586.98,28.14,81.53,6.09,6.99
유비쿼스홀딩스,신규상장,6100,2009-01-23,10290000,62769000000,48.35,26.28,40.40,28.89,21.69,24.73,45.45,472.90,435.93,25.03,NaN,7.45,16.23
대성파인텍,신규상장,3500,2009-01-23,2894000,10129000000,18.69,13.18,18.51,13.90,22.29,13.51,7.08,227.45,200.78,87.45,6.64,3.65,11.09
이수앱지스,신규상장,5500,2009-02-03,7443330,40938315000,53.43,-170.86,-37.02,25.54,7.53,44.54,-1.05,1012.28,859.09,45.09,-41.92,5.97,2.09
중국식품포장,신규상장,1500,2009-03-27,20000000,30000000000,15.99,11.28,40.84,3.39,15.68,1509.29,2356.57,179.05,119.33,65.06,NaN,8.45,10.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
컴퍼니케이,신규상장,4500,2019-05-23,15610000,70245000000,79.26,54.88,25.75,74.25,55.22,-51.79,-59.53,34.53,NaN,24.02,90.93,NaN,NaN
마이크로디지탈,신규상장,23000,2019-06-05,3630800,83508400000,33.28,-25.98,-35.62,3.72,-349.01,4.16,1428.78,510.88,428.15,31.88,-8.96,3.42,4.29
까스텔바작,신규상장,12000,2019-06-10,6596700,79160400000,63.15,15.78,NaN,NaN,NaN,NaN,NaN,441.99,196.22,26.25,NaN,NaN,NaN
압타바이오,신규상장,30000,2019-06-12,10881733,326451990000,100.00,-231.21,-28.49,384.60,-64.59,-49.73,-114.02,1696.50,1696.50,11.01,-5.19,449.15,NaN
엠에프엠코리아,신규상장,2000,2019-06-19,4310000,8620000000,6.65,1.05,2.74,20.91,-64.10,-16.70,-19.68,141.48,91.33,110.87,1.47,4.49,7.37

In [62]:
temp = X_train[['IPO_PBR','IPO_EV/EBIDTA']]

In [63]:
temp.isnull().sum()

IPO_PBR          1
IPO_EV/EBIDTA    2
dtype: int64

In [66]:
temp[temp.isnull().sum(axis=1)!=0]

           IPO_PBR  IPO_EV/EBIDTA
종목명
에스앤씨엔진그룹  3.075992            NaN
글로벌에스엠    1.889184            NaN
완리             NaN       4.104988

# 이 아래는 쓰다만 작업 일단 보류

In [81]:
CHLV = MatchItem_Calind(IPOcoms, X_train, Trading, '상장일',1)

In [106]:
def CalM(C,H,L):
    M = (C+H+L)/3
    M = np.unique(M)
    return M
def CalD(M,Mu):
    Diff = np.abs(M - Mu)
    D = np.mean(Diff)
    return D
def CalCCI(C,H,L):
    M = CalM(C,H,L)
    Mu = np.mean(M)
    D = CalD(M,Mu)
    CCI = (M - Mu) / D*0.015
    return CCI

In [107]:
CalCCI(C,H,L)

array([-0.03051489, -0.027789  , -0.01506815, -0.01476527, -0.01325088,
       -0.01294801, -0.01113074, -0.00810197, -0.00749621, -0.00719334,
       -0.00174154,  0.00098435,  0.00189298,  0.00552751,  0.00764765,
        0.00855628,  0.01703685,  0.02582029,  0.03884402,  0.04369006])

In [64]:
CHLV

          2009-01-16 2009-01-17 2009-01-18 2009-01-19 2009-01-20 2009-01-21  \
Name Item
메디톡스 종가       15,500     15,500     15,500     17,800     18,250     17,800
     고가       15,500     15,500     15,500     17,800     20,200     19,250
     저가       13,050     13,050     13,050     16,300     17,850     16,300
     거래량   2,094,307  2,094,307  2,094,307    659,898  2,088,228  1,354,483

          2009-01-22 2009-01-23 2009-01-24 2009-01-25  ... 2009-02-07  \
Name Item                                              ...
메디톡스 종가       15,850     14,250     14,250     14,250  ...     16,150
     고가       18,500     16,000     16,000     16,000  ...     16,400
     저가       15,650     14,250     14,250     14,250  ...     15,350
     거래량     780,928    811,816    811,816    811,816  ...    339,793

          2009-02-08 2009-02-09 2009-02-10 2009-02-11 2009-02-12 2009-02-13  \
Name Item
메디톡스 종가       16,150     15,750     15,600     16,050     16,200     17,050
     고가       16,400     16,400     16,100     16,500     17,050     17,400
     저가       15,350     15,700     15,550     15,200     16,150     16,050
     거래량     339,793    163,400    118,666    331,706    584,185    520,455

          2009-02-14 2009-02-15 2009-02-16
Name Item
메디톡스 종가       17,050     17,050     19,000
     고가       17,400     17,400     19,500
     저가       16,050     16,050     17,000
     거래량     520,455    520,455  1,816,885

[4 rows x 32 columns]

In [82]:
C = np.array(CHLV.loc[(slice(None),'종가'),:].astype('float64'))
H = np.array(CHLV.loc[(slice(None),'고가'),:].astype('float64'))
L = np.array(CHLV.loc[(slice(None),'저가'),:].astype('float64'))
V = np.array(CHLV.loc[(slice(None),'거래량'),:].astype('float64'))