In [2]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
from dateutil.relativedelta import relativedelta
from datetime import datetime
from dateutil.parser import parse
import copy

from imblearn.over_sampling import SMOTE
#시각화
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.metrics import *
from sklearn.metrics import accuracy_score, confusion_matrix, log_loss

##알고리즘 
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [72]:
# 다양한 오차 측정 지표를 확인하기 위한 함수 정의

from sklearn.metrics import *

def get_clf_eval(y_test, y_data, pred=None, pred_proba=None): 
    confusion = confusion_matrix(y_test, pred) 
    accuracy = accuracy_score(y_test, pred) 
    precision = precision_val(y_data)
    recall = recall_val(y_data) 
    f1 = f1_score(y_test, pred , average= 'weighted') 
    
#     print('정확도(accuracy): {0:.4f}, 정밀도(precision): {1:.4f}, 재현율(recall): {2:.4f}, f1_score: {3:.4f}'.format(accuracy, precision, recall, f1))
    
#     confusion = confusion_matrix(y_test, pred) 
#     accuracy = accuracy_score(y_test, pred) 
#     precision = precision_score(y_test, pred , average= 'macro') 
#     recall = recall_score(y_test, pred , average= 'macro') 
#     f1 = f1_score(y_test, pred , average= 'macro') 
    
#     print('정확도(accuracy): {0:.4f}, 정밀도(precision): {1:.4f}, 재현율(recall): {2:.4f}, f1_score: {3:.4f}'.format(accuracy, precision, recall, f1))
    
    return [accuracy, precision, recall, f1]

In [13]:
def Cut(Series , cuts):
    "구분할 iter가능한 변수와 구분 기준을 입력받으면 구분 기준 앞에서 부터 1로 구분해서 return 함"
    Cuts = copy.deepcopy(cuts)
    Cuts.append(np.inf)
    Cuts.insert(0,-1*np.inf)
    R = len(Cuts)
    label = range(1,R)
    return pd.cut(Series, Cuts, labels = label)

# 데이터 불러오기

In [43]:
df_1_3 = pd.read_csv("d:/공모전/IPO/IPO/CleanData/X_train_After_IPO_1.csv")
df_3_6 = pd.read_csv("d:/공모전/IPO/IPO/CleanData/X_train_After_IPO_3.csv")
df_0 = pd.read_csv("d:/공모전/IPO/IPO/CleanData/X_train_Before_IPO.csv")
df_end = pd.read_csv("d:/공모전/IPO/IPO/CleanData/X_train_EndPrice_IPO.csv",encoding = "cp949")

In [44]:
df_0_1 = df_0.drop(['공모가 대비 3개월 수익률','공모가 대비 6개월 수익률'],axis =1)
df_0_3 = df_0.drop(['공모가 대비 1개월 수익률','공모가 대비 6개월 수익률'],axis =1)
df_0_6 = df_0.drop(['공모가 대비 1개월 수익률','공모가 대비 3개월 수익률'],axis =1)

In [45]:
df_end_1 = df_end.drop(['종가 대비 3개월 수익률','종가 대비 6개월 수익률'],axis =1)
df_end_3 = df_end.drop(['종가 대비 1개월 수익률','종가 대비 6개월 수익률'],axis =1)
df_end_6 = df_end.drop(['종가 대비 1개월 수익률','종가 대비 3개월 수익률'],axis =1)

# 공통 전처리 및 랜덤포레스트

In [35]:
## 기본 전처리
df_0_1['상장일'] = pd.to_datetime(df_0_1['상장일'])
df_0_1 = df_0_1.set_index(['상장일'])
df_0_1 = df_0_1.drop(['종목명','공모 시가총액'],axis = 1) ## 나중에 카테고리 진행할려면 남겨줄 것
if y_name == '공모가 대비 6개월 수익률' or "종가 대비 6개월 수익률":
    df_0_1['Cat'] = Cut(df_0_1[y_name],[ -0.2, 0.2, 0.4])


else :
    df_0_1['Cat'] = Cut(df_0_1[y_name],[ -0.1, 0.1, 0.2])

NameError: name 'y_name' is not defined

In [36]:

## train 3년 test 1년으로 총 기간을 3개월 이동으로 36개 구간분할
train_list = []
test_list = []
train_start_date = '2009-04-01' ## 기한은 나중에 변경할수도
test_start_date = parse(str(train_start_date)).date() + relativedelta(years =4)
train_end_date = parse(str(test_start_date)).date() - relativedelta(days =1)
test_end_date = parse(str(train_end_date)).date() + relativedelta(years =1)

while True:

    train_list.append(df_0_1[train_start_date : train_end_date])
    test_list.append(df_0_1[test_start_date : test_end_date])

    train_start_date = parse(str(train_start_date)).date() + relativedelta(months=3)
    test_start_date = parse(str(test_start_date)).date() + relativedelta(months=3)
    train_end_date = parse(str(train_end_date)).date() + relativedelta(months=3)
    test_end_date = parse(str(test_end_date)).date() + relativedelta(months=3)

    if str(train_start_date) == '2017-04-01':
        break

In [40]:
train_list[0]

,매출총이익률,유동비율,부채비율,매출액증가율,IPO_PER,IPO_PBR,IPO_EV/EBITDA,1년전 대비 시장 회전율,1년 전 대비 시장수익률,1년 전 대비 고객예탁금 증감률,상장일 기준 국고3년시장금리,공모가 대비 1개월 수익률
상장일,,,,,,,,,,,,
2009-04-07,0.265039,1.521216,1.267154,0.222942,10.591051,3.309631,8.426986,610.422281,-0.441706,-0.002811,3.94,1.851064
2009-04-10,0.588840,6.590178,0.116098,0.272506,8.812247,2.705098,7.694457,614.854717,-0.420972,-0.051091,3.88,1.011111
2009-04-14,0.274725,1.772446,0.931424,0.347534,11.324829,1.457127,4.381342,620.091425,-0.392743,0.049892,3.78,0.425000
2009-04-17,0.142112,0.850896,2.723670,0.144142,6.829342,2.583655,4.703349,624.293086,-0.384882,0.102990,3.72,0.783333
2009-04-17,0.290372,1.294781,1.410724,0.071950,14.414761,3.301923,6.625795,624.293086,-0.384882,0.102990,3.72,0.641860
...,...,...,...,...,...,...,...,...,...,...,...,...
2013-02-07,0.409423,0.471443,1.514802,-0.099354,7.413107,1.956044,4.033972,632.177275,-0.019940,-0.139627,2.72,0.135556
2013-02-13,0.412796,0.474855,1.700041,0.956915,22.896633,11.326468,15.000695,624.461650,-0.033328,-0.148763,2.73,0.400000
2013-02-19,0.508247,1.226096,2.509999,0.202158,16.257772,4.276830,6.863808,617.441843,-0.051653,-0.136869,2.69,0.674699
2013-03-05,0.309552,1.518137,-7.070786,0.613232,-31.997723,-24.050556,10364.241120,610.107189,-0.077037,-0.105058,2.63,0.231250
2013-03-07,0.203606,0.171335,2.790872,0.121211,10.516663,2.498440,2.265116,608.893004,-0.057655,-0.171603,2.66,-0.058750

In [23]:
from imblearn.over_sampling import SMOTE

In [24]:
from imblearn.over_sampling import RandomOverSampler

In [131]:
def process_final(df,y_name):
    
    ## 기본 전처리
    df['상장일'] = pd.to_datetime(df['상장일'])
    df = df.set_index(['상장일'])
    df = df.drop(['종목명','공모 시가총액'],axis = 1) ## 나중에 카테고리 진행할려면 남겨줄 것
    if y_name == '공모가 대비 6개월 수익률' or "종가 대비 6개월 수익률":
        df['Cat'] = Cut(df[y_name],[ -0.2, 0.2, 0.4])
       
        
    else :
        df['Cat'] = Cut(df[y_name],[ -0.1, 0.1, 0.2])
       
    
    ## train 3년 test 1년으로 총 기간을 3개월 이동으로 36개 구간분할
    train_list = []
    test_list = []
    train_start_date = '2009-04-01' ## 기한은 나중에 변경할수도
    test_start_date = parse(str(train_start_date)).date() + relativedelta(years =3)
    train_end_date = parse(str(test_start_date)).date() - relativedelta(days =1)
    test_end_date = parse(str(train_end_date)).date() + relativedelta(years =1) +relativedelta(months=6)

    while True:

        train_list.append(df[train_start_date : train_end_date])
        test_list.append(df[test_start_date : test_end_date])

        train_start_date = parse(str(train_start_date)).date() + relativedelta(months=3)
        test_start_date = parse(str(test_start_date)).date() + relativedelta(months=3)
        train_end_date = parse(str(train_end_date)).date() + relativedelta(months=3)
        test_end_date = parse(str(test_end_date)).date() + relativedelta(months=3)

        if str(train_start_date) == '2017-10-01':
            break
            
    y_data = []
    score_list = []
    feature_list = []

    for i in range(0,len(train_list)):
        X_train_before = train_list[i].drop([y_name,'Cat'],axis =1)
        y_train_before = train_list[i]['Cat']
        X_test = test_list[i].drop([y_name,'Cat'],axis =1)
        y_test = test_list[i]['Cat']
        
#         smote = SMOTE(random_state=0,k_neighbors = 3)
#         X_train,y_train = smote.fit_resample(X_train_before,y_train_before)
        ros = RandomOverSampler()
        X_train,y_train = ros.fit_resample(X_train_before,y_train_before)

       # 랜덤 포레스트 학습 및 별도의 테스트 셋으로 예측 성능 평가
              
        clf = RandomForestClassifier(random_state=0 , max_depth = 5 , min_samples_leaf = 6 , min_samples_split =  12 , \
                                     n_estimators = 20 )
        

        clf.fit(X_train , y_train)
        train_pred = clf.predict(X_train_before)
        test_pred = clf.predict(X_test)




        #feature_importance
        feature_importance = clf.feature_importances_


        pred_value = pd.Series(test_pred,index = y_test.index)
        per = test_list[i][y_name]
        y_testdata = pd.concat([per,y_test,pred_value] , axis = 1)
        y_testdata.columns = ['실제 y 수익률','실제 y라벨링','예측 y 라벨링']
        
        train_pred_value = pd.Series(train_pred,index = y_train_before.index)
        per = train_list[i][y_name]
        y_traindata = pd.concat([per,y_train_before,train_pred_value] , axis = 1)
        y_traindata.columns = ['실제 y 수익률','실제 y라벨링','예측 y 라벨링']
        
        
        # 성과 평가
        train_res = get_clf_eval(y_train_before, y_traindata, train_pred)
        test_res = get_clf_eval(y_test, y_testdata,test_pred)
        res = train_res + test_res
        
        score_list.append(res)
        feature_list.append(feature_importance)
        y_data.append(y_testdata)   
    df_score = pd.DataFrame(score_list,columns = ["정확도","정밀도","재현율","f1_score"]+["정확도_test","정밀도_test","재현율_test","f1_score_test"]).T 
    df_score.rename(columns = lambda x : "model_set_"+ str(x),inplace = True)

    df_feature = pd.DataFrame(feature_list,columns = X_train.columns).T 
    df_feature.rename(columns = lambda x : "model_set_"+ str(x),inplace = True)
        
    return df_score , df_feature , y_data

In [103]:
df_score_0_1,df_feature_0_1,y_data_0_1 = process_final(df_0_1,'공모가 대비 1개월 수익률')

In [132]:
df_score_0_1,df_feature_0_1,y_data_0_1 = process_final(df_0_1,'공모가 대비 1개월 수익률')
df_score_0_3,df_feature_0_3,y_data_0_3 = process_final(df_0_3,'공모가 대비 3개월 수익률')
df_score_0_6,df_feature_0_6,y_data_0_6 = process_final(df_0_6,'공모가 대비 6개월 수익률')
df_score_1_3,df_feature_1_3,y_data_1_3 = process_final(df_1_3,'1_3_수익률')
df_score_3_6,df_feature_3_6,y_data_3_6 = process_final(df_3_6,'3_6_수익률')
df_score_end_1,df_feature_end_1,y_data_end_1 = process_final(df_end_1,'종가 대비 1개월 수익률')
df_score_end_3,df_feature_end_3,y_data_end_3 = process_final(df_end_3,'종가 대비 3개월 수익률')
df_score_end_6,df_feature_end_6,y_data_end_6 = process_final(df_end_6,'종가 대비 6개월 수익률')

In [121]:
df_score_0_1

,model_set_0,model_set_1,model_set_2,model_set_3,model_set_4,model_set_5,model_set_6,model_set_7,model_set_8,model_set_9,...,model_set_20,model_set_21,model_set_22,model_set_23,model_set_24,model_set_25,model_set_26,model_set_27,model_set_28,model_set_29
정확도,0.744048,0.740260,0.780000,0.768750,0.765101,0.790210,0.791367,0.671141,0.776978,0.726027,...,0.739316,0.711297,0.716049,0.756198,0.708502,0.698745,0.622951,0.682403,0.652361,0.706897
정밀도,0.736111,0.683333,0.750000,0.716418,0.734375,0.774194,0.842105,0.736111,0.871429,0.852941,...,0.735849,0.695652,0.807229,0.720430,0.685185,0.620690,0.561983,0.596154,0.533333,0.620370
재현율,0.868852,0.836735,0.900000,0.872727,0.854545,0.888889,0.872727,0.791045,0.897059,0.794521,...,0.829787,0.851064,0.697917,0.779070,0.831461,0.878049,0.829268,0.861111,0.901408,0.905405
f1_score,0.748857,0.745360,0.781907,0.771396,0.762465,0.792105,0.792250,0.670734,0.778885,0.725648,...,0.744174,0.716926,0.716940,0.756668,0.714347,0.707729,0.645633,0.697856,0.656890,0.708247
정확도_test,0.244444,0.347826,0.318182,0.269841,0.315789,0.381818,0.392523,0.273810,0.362637,0.266667,...,0.348837,0.365385,0.371134,0.405405,0.456522,0.311321,0.336538,0.376623,0.304348,0.369231
정밀도_test,0.444444,0.538462,0.549020,0.561404,0.492063,0.530864,0.464789,0.418919,0.419355,0.333333,...,0.354839,0.318182,0.400000,0.363636,0.482759,0.525000,0.582090,0.678571,0.736842,0.697674
재현율_test,0.173913,0.756757,0.800000,0.914286,0.815789,0.811321,0.634615,0.885714,0.764706,0.666667,...,0.423077,0.225806,0.148148,0.173913,0.424242,0.428571,0.684211,0.760000,0.291667,0.666667
f1_score_test,0.213614,0.262846,0.275336,0.215873,0.259127,0.374754,0.378409,0.176798,0.377836,0.267701,...,0.350801,0.373373,0.330213,0.371646,0.435742,0.310489,0.340355,0.349530,0.302940,0.347689

In [108]:
return_ex = pd.concat([frame(y_data_0_1),frame(y_data_0_3),frame(y_data_0_6),frame(y_data_1_3),frame(y_data_3_6),frame(y_data_end_1),frame(y_data_end_3),frame(y_data_end_6)],axis= 1)

In [109]:
ret = return_ex["mean"]

In [110]:
name = ['공모가 대비 1개월']+ ['공모가 대비 3개월']+ ['공모가 대비 6개월'] + ['1개월 대비 3개월']  + ["3개월 대비 6개월"]+ ["종가 대비 1개월"] +["종가 대비 3개월"] + ["종가 대비 6개월"]

In [112]:
ret.columns = name

In [113]:
ret

,공모가 대비 1개월,공모가 대비 3개월,공모가 대비 6개월,1개월 대비 3개월,3개월 대비 6개월,종가 대비 1개월,종가 대비 3개월,종가 대비 6개월
buy_sell수익률,0.207431,0.167946,0.157819,0.021995,0.049307,0.017943,-0.004047,0.003422
buy수익률,0.312045,0.328656,0.336493,0.049505,0.067577,-0.015193,0.037578,0.053541
all수익률,0.278544,0.320696,0.379675,0.052321,0.049369,-0.010451,0.039223,0.091430

In [275]:
ret.to_csv("수익률정리.csv",encoding = 'euc-kr')

In [276]:
df_score_0_1.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/모델 평가/0_1_모델 평가.csv",encoding = 'euc-kr')
df_score_0_3.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/모델 평가/0_3_모델 평가.csv",encoding = 'euc-kr')
df_score_0_6.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/모델 평가/0_6_모델 평가.csv",encoding = 'euc-kr')
df_score_1_3.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/모델 평가/1_3_모델 평가.csv",encoding = 'euc-kr')
df_score_3_6.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/모델 평가/3_6_모델 평가.csv",encoding = 'euc-kr')
df_score_end_1.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/모델 평가/end_1_모델 평가.csv",encoding = 'euc-kr')
df_score_end_3.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/모델 평가/end_3_모델 평가.csv",encoding = 'euc-kr')
df_score_end_6.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/모델 평가/end_6_모델 평가.csv",encoding = 'euc-kr')

In [277]:
df_feature_0_1.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/0_1_feature별 값.csv",encoding = 'euc-kr')
df_feature_0_3.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/0_3_feature별 값.csv",encoding = 'euc-kr')
df_feature_0_6.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/0_6_feature별 값.csv",encoding = 'euc-kr')
df_feature_1_3.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/1_3_feature별 값.csv",encoding = 'euc-kr')
df_feature_3_6.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/3_6_feature별 값.csv",encoding = 'euc-kr')
df_feature_end_1.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/end_1_feature별 값.csv",encoding = 'euc-kr')
df_feature_end_3.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/end_3_feature별 값.csv",encoding = 'euc-kr')
df_feature_end_6.to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/end_6_feature별 값.csv",encoding = 'euc-kr')

In [133]:
frame(y_data_0_1).to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/종속변수 수익률/0_1_수익률.csv",encoding = 'euc-kr')
frame(y_data_0_3).to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/종속변수 수익률/0_3_수익률.csv",encoding = 'euc-kr')
frame(y_data_0_6).to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/종속변수 수익률/0_6_수익률.csv",encoding = 'euc-kr')
frame(y_data_1_3).to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/종속변수 수익률/1_3_수익률.csv",encoding = 'euc-kr')
frame(y_data_3_6).to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/종속변수 수익률/3_6_수익률.csv",encoding = 'euc-kr')
frame(y_data_end_1).to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/종속변수 수익률/end_1_수익률.csv",encoding = 'euc-kr')
frame(y_data_end_3).to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/종속변수 수익률/end_3_수익률.csv",encoding = 'euc-kr')
frame(y_data_end_6).to_csv("D:/공모전/IPO/IPO/Result/랜덤포레스트/종속변수 수익률/end_6_수익률.csv",encoding = 'euc-kr')

In [123]:
def buy_sell(y_data):
    portfolio = []
    for i in range(len(y_data)):
        buy = y_data[i][y_data[i]['예측 y 라벨링'] > 2]['실제 y 수익률']
        sell = y_data[i][y_data[i]['예측 y 라벨링'] < 2]['실제 y 수익률']
        sum_1 = buy.sum() - sell.sum()
        sum_2 = len(buy)+len(sell)
        value = sum_1/sum_2
        portfolio.append(value)
    data = pd.DataFrame(portfolio).T
    data.rename(index = {0 : "buy_sell수익률"},columns = lambda x : "model_set_"+ str(x),inplace = True )
    data['mean'] = data.mean(axis=1)[0]
                         
    return data

In [124]:
def buy(y_data):
    portfolio = []
    for i in range(len(y_data)):
        buy = y_data[i][y_data[i]['예측 y 라벨링'] > 2]['실제 y 수익률']
        sum_1 = buy.sum()
        sum_2 = len(buy)
        value = sum_1/sum_2
        portfolio.append(value)
    data = pd.DataFrame(portfolio).T
    data.rename(index = {0 : "buy수익률"},columns = lambda x : "model_set_"+ str(x),inplace = True )
    data['mean'] = data.mean(axis=1)[0]
                         
    return data

In [125]:
def mean(y_data):
    portfolio = []
    for i in range(len(y_data)):
        buy = y_data[i]['실제 y 수익률']
        sum_1 = buy.sum()
        sum_2 = len(buy)
        value = sum_1/sum_2
        portfolio.append(value)
    data = pd.DataFrame(portfolio).T
    data.rename(index = {0 : "all수익률"},columns = lambda x : "model_set_"+ str(x),inplace = True )
    data['mean'] = data.mean(axis=1)[0]
    return data

In [126]:
def frame(y_data):
    buy_frame = buy(y_data)
    buy_sell_frame = buy_sell(y_data)
    mean_frame = mean(y_data)
    value = pd.concat([buy_sell_frame,buy_frame,mean_frame])
    return value

In [55]:
def precision_val(y_data):
    print(y_data)
    pre = []
    for i in range(0,32):
        new = y_data[i][y_data[i]['예측 y 라벨링'] > 2]
        real = new[new['실제 y라벨링'] > 2]
        if len(new) == 0:
            per = 0
        else :
            per = len(real)/len(new)
        pre.append(per)
    data = pd.DataFrame(pre).T
    data.rename(index = {0 : "특이도"},columns = lambda x : "model_set_"+ str(x),inplace = True )
    return data

In [70]:
def precision_val(y_data):
    

    new = y_data[y_data['예측 y 라벨링'] > 2]
    real = new[new['실제 y라벨링'] > 2]
    if len(new) == 0:
        per = 0
    else :
        per = len(real)/len(new)
    return per

In [71]:
def recall_val(y_data):

    real = y_data[y_data['실제 y라벨링'] > 2]
    new = real[real['예측 y 라벨링'] > 2]
    if len(new) == 0:
        per = 0
    else :
        per = len(new)/len(real)
    return per

In [51]:
def recall_val(y_data):
    pre = []
    for i in range(0,32):
        new = y_data[i][y_data[i]['실제 y라벨링'] > 2]
        real = new[new['예측 y 라벨링'] > 2]
        if len(new) == 0:
            per = 0
        else :
            per = len(real)/len(new)
        pre.append(per)
    data = pd.DataFrame(pre).T
    data.rename(index = {0 : "재현율"},columns = lambda x : "model_set_"+ str(x),inplace = True )
    return data

In [11]:
def value(y_data):
    pre = precision(y_data)
    rec = recall(y_data)
    cat = pd.concat([pre,rec])
    return cat

In [284]:
last = value(y_data_0_1)
a = value(y_data_0_3)
b = value(y_data_0_6)
c = value(y_data_1_3)
d = value(y_data_3_6)
e = value(y_data_end_1)
f = value(y_data_end_3)
g = value(y_data_end_6)

In [285]:
data = pd.concat([last,a,b,c,d,e,f,g])

In [286]:
data["mean"] = data.mean(axis=1)

In [288]:
data.to_csv("특이도재현율.csv", encoding = 'euc-kr')

In [84]:
y_data_0_1[0][y_data_0_1[0]['예측 y 라벨링'] == 3 | 4]

Empty DataFrame
Columns: [실제 y 수익률, 실제 y라벨링, 예측 y 라벨링]
Index: []

In [106]:
y_data_0_1[0][y_data_0_1[0]['예측 y 라벨링'] >= 3 ]

            실제 y 수익률 실제 y라벨링  예측 y 라벨링
상장일
2013-04-03  0.948718       4         3
2013-07-17  0.284091       3         4
2013-11-19  0.416000       4         3
2013-11-26 -0.179825       2         3
2013-12-19  0.252727       3         3
2014-02-04  1.444444       4         4
2014-02-27  0.700000       4         3

In [83]:
precision(y_data_0_1).to_csv("0_1_특이도.csv",encoding = 'euc-kr')
precision(y_data_0_3).to_csv("0_3_특이도.csv",encoding = 'euc-kr')
precision(y_data_0_6).to_csv("0_6_특이도.csv",encoding = 'euc-kr')
precision(y_data_1_3).to_csv("1_3_특이도.csv",encoding = 'euc-kr')
precision(y_data_3_6).to_csv("3_6_특이도.csv",encoding = 'euc-kr')
precision(y_data_end_1).to_csv("end_1_특이도.csv",encoding = 'euc-kr')
precision(y_data_end_3).to_csv("end_3_특이도.csv",encoding = 'euc-kr')
precision(y_data_end_6).to_csv("end_6_특이도.csv",encoding = 'euc-kr')

In [163]:
data = frame(y_data_0_1)

In [164]:
data

,model_set_0,model_set_1,model_set_2,model_set_3,model_set_4,model_set_5,model_set_6,model_set_7,model_set_8,model_set_9,...,model_set_23,model_set_24,model_set_25,model_set_26,model_set_27,model_set_28,model_set_29,model_set_30,model_set_31,mean
buy_sell수익률,-0.044068,0.372579,0.168851,0.509503,0.31087,0.453106,0.576705,0.375232,0.317349,0.030706,...,0.080933,0.034583,0.026071,0.174653,0.242369,-0.373427,0.045997,0.479256,0.652271,0.171183
buy수익률,0.552308,0.372579,0.168851,0.509503,0.31087,0.453106,0.628879,0.388828,0.330081,0.265080,...,0.116751,0.035872,0.070771,0.234856,0.436221,0.463664,0.582751,0.701041,0.652271,0.308671
all수익률,0.384893,0.315134,0.200451,0.503997,0.46273,0.452607,0.492498,0.379251,0.363375,0.333337,...,0.094258,0.038416,0.085447,0.213681,0.501264,0.611981,0.613520,0.742035,0.652271,0.324157