In [1]:
import pandas as pd
import numpy as np
from dateutil.relativedelta import relativedelta
from datetime import datetime
from dateutil.parser import parse

In [2]:
ipo_kq = pd.read_csv("d:/공모전/IPO/IPO/Data/KQ_IPO.csv")
trading_kq = pd.read_csv("d:/공모전/DATA/KQ_Trading.csv")
finance_kq = pd.read_csv("d:/공모전/IPO/IPO/Data/KQ_Finance.csv")
market_kq = pd.read_csv("d:/공모전/IPO/IPO/Data/KQ_Market.csv")

In [3]:
stock_kq = pd.read_csv("d:/공모전/DATA/상장주식수.csv",thousands=',')
stock = stock_kq.copy()

In [4]:
## 복사본 생성
ipo = ipo_kq.copy()
trading = trading_kq.copy()
finance = finance_kq.copy()
market = market_kq.copy()

In [6]:
pip install import_ipynb

Collecting import_ipynb
  Downloading import-ipynb-0.1.3.tar.gz (4.0 kB)
Building wheels for collected packages: import-ipynb
  Building wheel for import-ipynb (setup.py): started
  Building wheel for import-ipynb (setup.py): finished with status 'done'
  Created wheel for import-ipynb: filename=import_ipynb-0.1.3-py3-none-any.whl size=2975 sha256=bbc4c7c9659a7e349934cf8705834b9bef3e46a40d35986d8c6c5b29841f7545
  Stored in directory: c:\users\bbba2\appdata\local\pip\cache\wheels\fe\df\cf\1118a0b1acf475fb435463072bba11232db7e3592e7d7695d4
Successfully built import-ipynb
Installing collected packages: import-ipynb
Successfully installed import-ipynb-0.1.3
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\textmining\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\textmining\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\textmining\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\textmining\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\textmining\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\textmining\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\envs\textmining\lib\site-packages)

In [22]:
import import_ipynb
from Module import Preprocessing as mo

In [18]:
ipo = mo.ipo_processing(ipo)

In [21]:
ipo

              상장유형      공모가         상장일     상장주식수        경쟁률
종목명
코오롱생명과학       신규상장  23500.0  2009-04-07   3420000        NaN
뷰웍스           신규상장   9000.0  2009-04-10   6047910        NaN
에스앤에스텍        신규상장   4000.0  2009-04-14  10915980        NaN
에이테크솔루션       신규상장   5400.0  2009-04-17  10000000        NaN
엔에스브이         신규상장   4300.0  2009-04-17   8450000        NaN
...            ...      ...         ...       ...        ...
네오이뮨텍(Reg.S)  신규상장   7500.0  2021-03-16  98392010   664.65:1
바이오다인         신규상장  30000.0  2021-03-17   5918200       48:1
라이프시맨틱스       신규상장  12500.0  2021-03-23   9776917  1774.57:1
자이언트스텝        신규상장  11000.0  2021-03-24   9427965     2342:1
제노코           신규상장  36000.0  2021-03-24   2442140  2095.46:1

[739 rows x 5 columns]

In [23]:
trading = mo.FeatureDf_processing(trading)

In [24]:
stock = mo.FeatureDf_processing(stock)

In [27]:
Train_data = pd.read_csv("d:/공모전/Train_data_2.csv")

In [30]:
finance = mo.FeatureDf_processing(finance)

In [31]:
finance

                   2007-12-31  2008-12-31  2009-12-31  2010-12-31  \
Name    Item
코오롱생명과학 유동자산       25533779.0  32785073.0  46031375.0  44206298.0
        재고자산       10644432.0  15755548.0  15618696.0  19115141.0
        매출채권및기타채권   5648100.0   5388121.0  13565664.0   9965387.0
        당좌자산       14889346.0  17029524.0  30412677.0  25091156.0
        부채총계       21149619.0  30771151.0  29455912.0  26077140.0
...                       ...         ...         ...         ...
제노코     매출총이익             NaN         NaN         NaN         NaN
        영업이익              NaN         NaN         NaN         NaN
        당기순이익             NaN         NaN         NaN         NaN
        이자비용              NaN         NaN         NaN         NaN
        EBITDA2           NaN         NaN         NaN         NaN

                    2011-12-31   2012-12-31   2013-12-31   2014-12-31  \
Name    Item
코오롱생명과학 유동자산       97241204.04  77360599.50  86848312.03  68856857.49
        재고자산       27868369.44  35830022.56  43285477.91  42591550.57
        매출채권및기타채권  30166989.13  24744825.79  22196713.23  18057581.85
        당좌자산       69372834.61  41530576.94  43562834.13  26265306.92
        부채총계       76232230.22  85597257.82  83270342.39  72721184.54
...                        ...          ...          ...          ...
제노코     매출총이익              NaN          NaN   1656072.00   2379285.00
        영업이익               NaN          NaN    307088.00    838223.00
        당기순이익              NaN          NaN    302688.00    780894.00
        이자비용               NaN          NaN    156988.00    141036.00
        EBITDA2            NaN          NaN    577985.00   1183760.00

                    2015-12-31    2016-12-31    2017-12-31    2018-12-31  \
Name    Item
코오롱생명과학 유동자산       82379227.63  1.968163e+08  1.509757e+08  1.057165e+08
        재고자산       36251496.64  3.473386e+07  4.653150e+07  3.742710e+07
        매출채권및기타채권  17273450.97  2.146949e+07  2.169434e+07  2.452885e+07
        당좌자산       46127730.99  1.620824e+08  1.044442e+08  6.828944e+07
        부채총계       93174227.40  9.478449e+07  1.713845e+08  1.727575e+08
...                        ...           ...           ...           ...
제노코     매출총이익       2033891.00  2.793801e+06  4.973163e+06  3.490791e+06
        영업이익         258992.00  9.658260e+05  1.144857e+06  5.608490e+05
        당기순이익        170341.00  7.749900e+05  8.135220e+05  3.022800e+05
        이자비용         122896.00  1.185370e+05  1.125250e+05  1.131330e+05
        EBITDA2      713459.00  1.439875e+06  1.786844e+06  1.208647e+06

                     2019-12-31    2020-12-31
Name    Item
코오롱생명과학 유동자산       9.528992e+07  1.005631e+08
        재고자산       3.606386e+07  4.279038e+07
        매출채권및기타채권  2.945740e+07  3.494753e+07
        당좌자산       5.509605e+07  5.777268e+07
        부채총계       1.772743e+08  1.903806e+08
...                         ...           ...
제노코     매출총이익      1.555457e+06  5.454780e+06
        영업이익      -9.754658e+05  2.498825e+06
        당기순이익     -8.219248e+05  1.690996e+06
        이자비용       9.894544e+04  2.616420e+05
        EBITDA2   -3.829088e+05  3.347397e+06

[11774 rows x 14 columns]

In [33]:
IPOcoms = ipo.index

In [44]:
IPOcoms

Index(['코오롱생명과학', '뷰웍스', '에스앤에스텍', '에이테크솔루션', '엔에스브이', '에스티오', '티플랙스',
       '네프로아이티', '우림피티에스', '신텍',
       ...
       '유일에너테크', '뷰노', '나노씨엠에스', '프레스티지바이오로직스', '싸이버원', '네오이뮨텍(Reg.S)',
       '바이오다인', '라이프시맨틱스', '자이언트스텝', '제노코'],
      dtype='object', name='종목명', length=739)

In [39]:
def MatchItem_per_new(IPOcoms, FeatureDf, finding):
    """
    per/pbr/ev 등등 구하기
    """
    FeatureDf[finding] = np.nan
    for i in IPOcoms:
        IPOday = FeatureDf.loc[i,'상장일']
        
        if parse(IPOday).date().month < 4:
            day= datetime(parse(IPOday).year,12,31).date() - \
            relativedelta(years = 2)
        else :
            day = datetime(parse(IPOday).year,12,31).date() - \
            relativedelta(years = 1)
            
        num_1 = trading.loc[(i,'종가'),IPOday]
        num_2 = stock.loc[i,IPOday][0]
        num_3 = finance.loc[(i,'당기순이익'),str(day)]
        
        per = (num_1*num_2)/(num_3*1000)
        FeatureDf.loc[i,finding] = per
    return FeatureDf

In [42]:
def MatchItem_pbr_new(IPOcoms, FeatureDf, finding):
    """
    per/pbr/ev 등등 구하기
    """
    FeatureDf[finding] = np.nan
    for i in IPOcoms:
        IPOday = FeatureDf.loc[i,'상장일']
        
        
        if parse(IPOday).date().month < 4:
            day= datetime(parse(IPOday).year,12,31).date() - \
            relativedelta(years = 2)
        else :
            day = datetime(parse(IPOday).year,12,31).date() - \
            relativedelta(years = 1)
            
        num_1 = trading.loc[(i,'종가'),IPOday]
        num_2 = stock.loc[i,IPOday][0]
        num_3 = finance.loc[(i,'자본총계'),str(day)]
        
        pbr = (num_1*num_2)/(num_3*1000)
        FeatureDf.loc[i,finding] = pbr
    return FeatureDf

In [41]:
def MatchItem_ev_new(IPOcoms, FeatureDf, finding):
    """
    per/pbr/ev 등등 구하기
    """
    FeatureDf[finding] = np.nan
    for i in IPOcoms:
        IPOday = FeatureDf.loc[i,'상장일']

        
        if parse(IPOday).date().month < 4:
            day= datetime(parse(IPOday).year,12,31).date() - \
            relativedelta(years = 2)
        else :
            day = datetime(parse(IPOday).year,12,31).date() - \
            relativedelta(years = 1)
            
        num_1 = trading.loc[(i,'종가'),IPOday]
        num_2 = stock.loc[i,IPOday][0]
        num_3 = finance.loc[(i,'순부채'),str(day)]
        num_4 = finance.loc[(i,'EBITDA2'),str(day)]
        
        ebitda = (num_1*num_2 + num_3*1000)/(num_4*1000)
        FeatureDf.loc[i,finding] = ebitda
    return FeatureDf

In [46]:
Train_data.set_index("종목명",inplace =True)

In [47]:
Train_data = MatchItem_per_new(IPOcoms,Train_data,'종가_PER')

C:\ProgramData\Anaconda3\envs\textmining\lib\site-packages\ipykernel_launcher.py:17: PerformanceWarning: indexing past lexsort depth may impact performance.

In [49]:
Train_data = MatchItem_pbr_new(IPOcoms,Train_data,'종가_PBR')
Train_data = MatchItem_ev_new(IPOcoms,Train_data,'종가_EV/EBITDA')

C:\ProgramData\Anaconda3\envs\textmining\lib\site-packages\ipykernel_launcher.py:18: PerformanceWarning: indexing past lexsort depth may impact performance.

In [50]:
Train_data

,상장유형,공모가,상장일,상장주식수,경쟁률,공모 시가총액,매출총이익률,영업이익률,ROE,유동비율,...,IPO_EV/EBITDA,1개월 후 PER,3개월 후 PER,1개월 후 PBR,3개월 후 PBR,1개월 후 EV/EBITDA,3개월 후 EV/EBITDA,종가_PER,종가_PBR,종가_EV/EBITDA
종목명,,,,,,,,,,,,,,,,,,,,,
코오롱생명과학,신규상장,23500,2009-04-07,3420000,NaN,8.037000e+10,0.265039,0.116338,0.312493,1.521216,...,8.426986,35.328159,31.531700,11.039808,9.853440,28.338707,25.318059,24.336883,7.605109,19.593512
뷰웍스,신규상장,9000,2009-04-10,6047910,NaN,5.443119e+10,0.588840,0.295151,0.306970,6.590178,...,7.694457,17.722409,12.435060,5.440252,3.817194,14.652573,10.035405,20.268169,6.221725,16.875654
에스앤에스텍,신규상장,4000,2009-04-14,10915980,NaN,4.366392e+10,0.274725,0.147742,0.128667,1.772446,...,4.381342,21.593257,18.690432,2.778330,2.404833,9.836695,8.714033,26.047107,3.351391,11.559213
에이테크솔루션,신규상장,5400,2009-04-17,10000000,NaN,5.400000e+10,0.142112,0.070575,0.378317,0.850896,...,4.703349,12.178992,10.408422,4.607519,3.937682,9.617427,8.398360,15.682192,5.932838,12.029439
엔에스브이,신규상장,4300,2009-04-17,8450000,NaN,3.633500e+10,0.290372,0.172593,0.229065,1.294781,...,6.625795,23.667026,25.611343,5.421298,5.866673,12.563497,13.456981,33.153951,7.594424,16.923084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
네오이뮨텍(Reg.S),신규상장,7500,2021-03-16,98392010,664.65:1,7.379400e+11,NaN,NaN,-0.122516,36.478564,...,-47.776769,-41.674781,-33.921334,15.069535,12.265901,-39.659045,-31.860924,-99.446188,12.183762,-84.612480
바이오다인,신규상장,30000,2021-03-17,5918200,48:01:00,1.775460e+11,0.287352,-0.415186,-0.308154,0.517623,...,-312.620103,-101.107148,-61.966747,64.320102,39.420630,-745.809776,-460.310820,-124.411939,38.338011,-456.601910
라이프시맨틱스,신규상장,12500,2021-03-23,9776917,1774.57:1,1.222110e+11,1.000000,-3.079905,1.123510,0.611110,...,-37.077357,-13.391250,-12.284518,57.026603,52.313584,-43.690635,-40.005030,-43.169106,-48.500929,-53.029192
자이언트스텝,신규상장,11000,2021-03-24,9427965,2342:01:00,1.037080e+11,0.189292,-0.124993,-0.459224,1.438179,...,-266.429851,-312.902597,-355.962746,30.037340,34.170934,419.463705,477.997062,-85.812888,39.407363,-691.193581
제노코,신규상장,36000,2021-03-24,2442140,2095.46:1,8.791704e+10,0.051599,-0.032359,-0.122783,1.361835,...,-229.595933,81.308585,66.144462,16.767919,13.640687,38.659160,30.998739,-237.996723,29.221957,-503.689577

In [55]:
def return_rate_new(IPOcoms,FeatureDf,TargetDf,name,num):
    
    FeatureDf[name] = np.nan
    for i in IPOcoms:
        IPOday = FeatureDf.loc[i,'상장일']
        month = parse(IPOday).date() + relativedelta(months = num)
        month = str(month)
        ## 몇 개월 뒤 종가
        new_price = TargetDf.loc[(i,'종가'),month]
        ## 상장일 종가
        pre_price = TargetDf.loc[(i,'종가'),IPOday]
        ## 수익률
        return_rate = (new_price - pre_price)/pre_price
        FeatureDf.loc[i,name] = return_rate
    return FeatureDf

In [56]:
Train_data = return_rate_new(IPOcoms,Train_data,trading,'종가 대비 1개월 수익률',1)

In [58]:
Train_data = return_rate_new(IPOcoms,Train_data,trading,'종가 대비 3개월 수익률',3)
Train_data = return_rate_new(IPOcoms,Train_data,trading,'종가 대비 6개월 수익률',6)

In [59]:
Train_data = Train_data.drop("공모가 대비 1개월 수익률",axis =1)

In [65]:
Train_data.columns

Index(['상장유형', '공모가', '상장일', '상장주식수', '경쟁률', '공모 시가총액', '매출총이익률', '영업이익률',
       'ROE', '유동비율', '당좌비율', '부채비율', '이자보상배율', '매출채권회전율', '재고자산회전율', '매출액증가율',
       '영업이익증가율', 'IPO_PER', 'IPO_PBR', 'IPO_EV/EBITDA', '1개월 후 PER',
       '3개월 후 PER', '1개월 후 PBR', '3개월 후 PBR', '1개월 후 EV/EBITDA',
       '3개월 후 EV/EBITDA', '종가_PER', '종가_PBR', '종가_EV/EBITDA', '종가 대비 1개월 수익률',
       '종가 대비 3개월 수익률', '종가 대비 6개월 수익률'],
      dtype='object')

In [71]:
test = pd.read_csv("D:\공모전\IPO\IPO\CleanData/KQ_all.csv")

In [72]:
test.set_index("종목명",inplace =True)

In [73]:
test['종가_PER'] = Train_data['종가_PER']
test['종가_PBR'] = Train_data['종가_PBR']
test['종가_EV/EBITDA'] = Train_data['종가_EV/EBITDA']
test['종가 대비 1개월 수익률'] = Train_data['종가 대비 1개월 수익률']
test['종가 대비 3개월 수익률'] = Train_data['종가 대비 3개월 수익률']
test['종가 대비 6개월 수익률'] = Train_data['종가 대비 6개월 수익률']

In [77]:
test.to_csv("KQ_ALL_2.csv", encoding = 'euc-kr')